[tool.poetry]
name = "core"
version = "0.1.0"
description = ""
authors = ["Hamza Qureshi - Desktop <hamza7771.861@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
